<BookScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "50dp"

        Button:
            text: 'Tap for Google.\nBack button/gesture to return.'
            on_press: root.view_google()

        StencilAnchorLayout:
            ScatterLayout:
                do_rotation: False

                Image:
                    id: book_image
                    size: self.texture_size
