BoxLayout:
    orientation: 'vertical'

    Button:
        text: 'Tap for Google.\nBack button/gesture to return.'
        on_press: app.view_google()

    Button:
        text: 'Tap for local file.\nBack button/gesture to return.'
        on_press: app.view_local_file()

    Button:
        text: 'List downloads'
        on_press: app.view_downloads()

    Label:
        id: list_downloads
        text: ''
